include:
  - board: xiao_ble//zmk
    shield: cornix_dongle_adapter
    snippet: studio-rpc-usb-uart nrf52840-nosd
    cmake-args: -DCONFIG_ZMK_DISPLAY=n
    artifact-name: cornix_dongle

  - board: cornix_ph_left
    artifact-name: cornix_left_for_dongle

  - board: cornix_right
    artifact-name: cornix_right

  - board: cornix_right
    shield: settings_reset
    snippet: studio-rpc-usb-uart nrf52840-nosd
    artifact-name: cornix_reset

  - board: xiao_ble//zmk
    shield: settings_reset
    artifact-name: reset_dongle
