CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80

# --- Trackball integration (3rd peripheral) ---
# Left + Right + Trackball = 3 peripherals
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=3
# Receive trackball input over the split
CONFIG_ZMK_INPUT_SPLIT=y
